import type { FavoriteShop } from './favorite'

export const mockFavoriteShops: FavoriteShop[] = [
  {
    favoriteId: 1,
    shopId: 1,
    shopName: '스위트 드림즈 베이커리',
    shopImageUrl: 'https://placehold.co/400x300/FFC0CB/FFFFFF?text=Sweet+Dreams',
    averageRating: 4.8,
    minPrice: 35000,
    keywords: ['생일', '기념일', '파티'],
  },
  {
    favoriteId: 2,
    shopId: 2,
    shopName: '달콤한 순간',
    shopImageUrl: 'https://placehold.co/400x300/FFB6C1/FFFFFF?text=Sweet+Moment',
    averageRating: 4.5,
    minPrice: 28000,
    keywords: ['크리스마스', '기념일', '파티'],
  },
  {
    favoriteId: 3,
    shopId: 3,
    shopName: '메종 드 가토',
    shopImageUrl: 'https://placehold.co/400x300/DDA0DD/FFFFFF?text=Maison+Gateau',
    averageRating: 4.9,
    minPrice: 45000,
    keywords: ['생일', '웨딩', '파티'],
  },
  {
    favoriteId: 4,
    shopId: 4,
    shopName: '해피 버스데이',
    shopImageUrl: 'https://placehold.co/400x300/87CEEB/FFFFFF?text=Happy+Birthday',
    averageRating: 4.2,
    minPrice: 30000,
    keywords: ['생일', '돌잔치', '파티'],
  },
  {
    favoriteId: 5,
    shopId: 5,
    shopName: '러브 레터링',
    shopImageUrl: 'https://placehold.co/400x300/FF6B6B/FFFFFF?text=Love+Lettering',
    averageRating: 4.6,
    minPrice: 32000,
    keywords: ['기념일', '웨딩', '프러포즈'],
  },
  {
    favoriteId: 6,
    shopId: 6,
    shopName: '케이크 하우스',
    shopImageUrl: 'https://placehold.co/400x300/FFD700/FFFFFF?text=Cake+House',
    averageRating: 4.7,
    minPrice: 38000,
    keywords: ['생일', '기념일', '파티'],
  },
  {
    favoriteId: 7,
    shopId: 7,
    shopName: '파티시에 공방',
    shopImageUrl: 'https://placehold.co/400x300/98D8C8/FFFFFF?text=Patissier',
    averageRating: 4.4,
    minPrice: 42000,
    keywords: ['크리스마스', '웨딩', '파티'],
  },
  {
    favoriteId: 8,
    shopId: 8,
    shopName: '슈가 베이커리',
    shopImageUrl: 'https://placehold.co/400x300/F7CAC9/FFFFFF?text=Sugar+Bakery',
    averageRating: 4.3,
    minPrice: 33000,
    keywords: ['생일', '돌잔치', '기념일'],
  },
]
